# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='test_example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x0ctest_example\"8\n\x0ctest_Request\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x03\"1\n\rtest_Response\x12\x11\n\tstu_class\x18\x01 \x01(\t\x12\r\n\x05grade\x18\x02 \x01(\x03\x32O\n\x05model\x12\x46\n\ttest_show\x12\x1a.test_example.test_Request\x1a\x1b.test_example.test_Response\"\x00\x62\x06proto3')
)




_TEST_REQUEST = _descriptor.Descriptor(
  name='test_Request',
  full_name='test_example.test_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='test_example.test_Request.index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='test_example.test_Request.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='test_example.test_Request.age', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=84,
)


_TEST_RESPONSE = _descriptor.Descriptor(
  name='test_Response',
  full_name='test_example.test_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stu_class', full_name='test_example.test_Response.stu_class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grade', full_name='test_example.test_Response.grade', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['test_Request'] = _TEST_REQUEST
DESCRIPTOR.message_types_by_name['test_Response'] = _TEST_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

test_Request = _reflection.GeneratedProtocolMessageType('test_Request', (_message.Message,), dict(
  DESCRIPTOR = _TEST_REQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_example.test_Request)
  ))
_sym_db.RegisterMessage(test_Request)

test_Response = _reflection.GeneratedProtocolMessageType('test_Response', (_message.Message,), dict(
  DESCRIPTOR = _TEST_RESPONSE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_example.test_Response)
  ))
_sym_db.RegisterMessage(test_Response)



_MODEL = _descriptor.ServiceDescriptor(
  name='model',
  full_name='test_example.model',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=137,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='test_show',
    full_name='test_example.model.test_show',
    index=0,
    containing_service=None,
    input_type=_TEST_REQUEST,
    output_type=_TEST_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['model'] = _MODEL

# @@protoc_insertion_point(module_scope)
